version: "3.9"
services: 
    homework:
        image: kuzko/lesson2:latest
        ports: 
            - "80:80"
        networks: 
            - frontend
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
networks: 
    frontend: